[project]
name = "arxiv-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.11",
    "google-generativeai>=0.8.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
