name: Fetch arXiv Papers

on:
  schedule:
    - cron: '0 */3 * * *'  # 3時間ごとに実行
  workflow_dispatch:       # 手動実行も可能にする
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
  
        - name: Install uv
          uses: astral-sh/setup-uv@v3
          with:
            enable-cache: true
  
        - name: Set up Python
          run: uv python installs
  
        - name: Install the project
          run: uv sync --all-extras --dev
  
        - name: Run fetch_arxiv_papers.py
          run: uv run fetch_arxiv_papers.py