name: Fetch arXiv Papers

on:
  schedule:
    - cron: '0 */6 * * *'  # 3時間ごとに実行
  workflow_dispatch:  # 手動実行も可能にする
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run fetch_arxiv_papers.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: uv run source/fetch_arxiv_papers.py

      # git statusを確認し、変更があればコミットとプッシュを行う
      - name: Commit And Push contents info file if there are changes
        run: |
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/MidraLab/arxiv-sound-bot
          git config --global user.name "MidraLab"
          git config --global user.email "midralab@gmail.com"

          # 変更があるか確認
          if [ -n "$(git status --porcelain)" ]; then
            git add opt/contents_info.json
            git commit -m "Update index file"
            git push origin main
          else
            echo "No changes to commit"
          fi